rollback = """
drop table if exists grades;
drop table if exists niches;
drop table if exists complexes;
drop table if exists biomes;
drop table if exists biome_grades;
drop table if exists mutations;
create table mutations (_id integer primary key, grade_id integer not null, name text not null, points_left integer not null);
create table grades (_id integer primary key, name text not null);
create table niches (_id integer primary key, grade_id integer not null, amount integer not null, success integer not null);
create table biomes (_id integer primary key, name text not null, type text not null);
create table biome_grades (_id integer primary key, biome_id integer not null, grade_id integer not null, amount integer not null, success integer not null);
create table complexes (_id integer primary key, niche_id integer not null);
insert into biomes(name, type) values ("b", "geysers");
insert into grades(name) values("g");
"""