rollback = """
drop table if exists grades;
drop table if exists niches;
drop table if exists complexes;
create table grades (id integer primary key, name text not null);
create table niches (id integer primary key, grade_id integer not null, amount real not null);
create table complexes (id integer primary key, niche_id integer not null);
"""